
thread: thread.c
	gcc -Wall -Wpedantic -Wextra -Werror thread.c -o thread -lm -pthread

process: process.c
	gcc -Wall -Wpedantic -Wextra -Werror process.c -o process -lm

clean:
	rm -f process thread
